site_name: "SKYLINEEE PORTFOLIO"
site_description: "Портфолио и лабораторные работы"

theme:
  name: shadcn

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная работа 1: projects/lab8.md
      - Лабораторная работа 2: projects/lab9.md
